version: '3.8'

services:
  web:
    environment:
      - FLASK_ENV=development
      - DEBUG=true
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"