apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml
- hpa.yaml  # Horizontal Pod Autoscaler

namespace: terrafusion-prod

commonLabels:
  environment: prod

patches:
- path: replicas-patch.yaml
- path: resource-patch.yaml

configMapGenerator:
- name: terrafusion-config
  behavior: merge
  literals:
  - PGHOST=postgres-prod