apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrafusion-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: terrafusion
      component: api
  template:
    metadata:
      labels:
        app: terrafusion
        component: api
    spec:
      containers:
      - name: api
        image: terrafusion/terrafusion:latest
        ports:
        - containerPort: 5000
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: port
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: terrafusion-config
              key: flask_env
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai_api_key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: anthropic_api_key
        - name: MCP_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: mcp_api_key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: terrafusion-config