apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrafusion-api
  labels:
    app: terrafusion
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terrafusion
      component: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: terrafusion
        component: api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/terrafusion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: terrafusion-config
              key: PGHOST
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: terrafusion-config
              key: PGPORT
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: terrafusion-config
              key: PGUSER
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: terrafusion-config
              key: PGDATABASE
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: terrafusion-secrets
              key: PGPASSWORD
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: terrafusion-secrets
              key: SESSION_SECRET
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: terrafusion-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: terrafusion-secrets
              key: ANTHROPIC_API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 512Mi
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: terrafusion-config