apiVersion: v1
kind: Service
metadata:
  name: terrafusion-api
  labels:
    app: terrafusion
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: terrafusion
    component: api