apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: terrafusion-dev

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

configMapGenerator:
  - name: terrafusion-config
    behavior: merge
    literals:
      - flask_env=development
      - log_level=DEBUG
      - enable_metrics=true
      - max_workers=2