apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - staging-ingress.yaml

namespace: terrafusion-staging

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

configMapGenerator:
  - name: terrafusion-config
    behavior: merge
    literals:
      - flask_env=staging
      - log_level=INFO
      - enable_metrics=true
      - max_workers=4