apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: terrafusion-staging

commonLabels:
  environment: staging

patches:
- path: replicas-patch.yaml

configMapGenerator:
- name: terrafusion-config
  behavior: merge
  literals:
  - PGHOST=postgres-staging